apiVersion: v1
kind: Service
metadata:
  name: gitpanel
  namespace: <NAMESPACE>
  labels:
    app: gitpanel
    component: front
spec:
  selector:
    app: gitpanel
    component: app
    env: <ENV>
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitpanel
  namespace: <NAMESPACE>
  labels:
    app: gitpanel
    component: app
    env: <ENV>
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitpanel
      component: app
      env: <ENV>
  template:
    metadata:
      namespace: <NAMESPACE>
      labels:
        app: gitpanel
        component: app
        env: <ENV>
    spec:
      containers:
        - name: gitpanel
          imagePullPolicy: Always
          image: <IMAGE-APP>
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: github-registry
